package com.ailauncher.app.domain.models

import android.graphics.drawable.Drawable
import kotlinx.serialization.Serializable

/**
 * Runtime-only models — these never get serialised. AppInfo holds a Drawable,
 * so it can't even be @Serializable.
 */

data class AppInfo(
    val packageName: String,
    val label: String,
    val icon: Drawable?,
    val category: AppCategory,
    val isSystemApp: Boolean,
    val installTime: Long,
    val lastUpdateTime: Long
)

data class RankedApp(
    val app: AppInfo,
    val weightScore: Float,
    val usageMinutesToday: Long,
    val launchCountToday: Int,
    val lastUsedTimestamp: Long,
    val smartFolder: AppCategory,
    val notificationCount: Int = 0
)

data class SmartFolder(
    val category: AppCategory,
    val apps: List<RankedApp>,
    val isAutoGenerated: Boolean = true
)

data class UsageSnapshot(
    val packageName: String,
    val totalTimeInForeground: Long,
    val lastTimeUsed: Long,
    val launchCount: Int,
    val hourlyDistribution: Map<Int, Int>
)

/**
 * Top-level aggregator persisted by [com.ailauncher.app.data.SettingsRepository].
 * Each field maps to one DataStore preference key (see SettingsRepository.K_*).
 * Used as the JSON shape of backup/restore payloads.
 */
@Serializable data class LauncherSettings(
    val appearance: AppearanceSettings = AppearanceSettings(),
    val pages: PagesSettings = PagesSettings(),
    val security: SecuritySettings = SecuritySettings(),
    val backup: BackupSettings = BackupSettings(),
    val widgets: List<WidgetSlot> = emptyList(),
    val news: NewsSettings = NewsSettings(),
    val hiddenApps: HiddenAppsSettings = HiddenAppsSettings(),
    val smartControl: SmartControlSettings = SmartControlSettings(),
    val adaptiveDisplay: AdaptiveDisplaySettings = AdaptiveDisplaySettings(),
    val repair: RepairSettings = RepairSettings(),
    val onboarding: OnboardingState = OnboardingState()
)
