package com.ailauncher.app.domain.models

import android.graphics.drawable.Drawable
import androidx.compose.runtime.Immutable
import kotlinx.serialization.Serializable

/**
 * Runtime-only models — these never get serialised. AppInfo holds a Drawable,
 * so it can't even be @Serializable.
 */

/**
 * v9.3: @Immutable is an assertion, not a check — normally risky on a class
 * holding a platform [Drawable], since Compose can't verify Drawable's
 * mutability and would otherwise infer the whole class (and anything that
 * embeds it) as unstable, forcing every composable that takes a [RankedApp]
 * to recompose on every pass regardless of whether it actually changed. It's
 * safe here specifically because nothing renders [icon] directly — HomeAppItem
 * always goes through IconCache.getOrLoad, which converts to an immutable
 * ImageBitmap once and caches it by packageName, so in-place Drawable
 * mutation (setTint/setBounds) never reaches composition. Don't add a second
 * direct `Image(bitmap = ... icon ...)` call path without re-checking this.
 */
@Immutable
data class AppInfo(
    val packageName: String,
    val label: String,
    val icon: Drawable?,
    val category: AppCategory,
    val isSystemApp: Boolean,
    val installTime: Long,
    val lastUpdateTime: Long
)

@Immutable
data class RankedApp(
    val app: AppInfo,
    val weightScore: Float,
    val usageMinutesToday: Long,
    val launchCountToday: Int,
    val lastUsedTimestamp: Long,
    val smartFolder: AppCategory,
    val notificationCount: Int = 0
)

@Immutable
data class SmartFolder(
    val category: AppCategory,
    val apps: List<RankedApp>,
    val isAutoGenerated: Boolean = true
)

data class UsageSnapshot(
    val packageName: String,
    val totalTimeInForeground: Long,
    val lastTimeUsed: Long,
    val launchCount: Int,
    val hourlyDistribution: Map<Int, Int>
)

/**
 * Top-level aggregator persisted by [com.ailauncher.app.data.SettingsRepository].
 * Each field maps to one DataStore preference key (see SettingsRepository.K_*).
 * Used as the JSON shape of backup/restore payloads.
 */
@Serializable data class LauncherSettings(
    val appearance: AppearanceSettings = AppearanceSettings(),
    val pages: PagesSettings = PagesSettings(),
    val security: SecuritySettings = SecuritySettings(),
    val backup: BackupSettings = BackupSettings(),
    val widgets: List<WidgetSlot> = emptyList(),
    val news: NewsSettings = NewsSettings(),
    val hiddenApps: HiddenAppsSettings = HiddenAppsSettings(),
    val smartControl: SmartControlSettings = SmartControlSettings(),
    val adaptiveDisplay: AdaptiveDisplaySettings = AdaptiveDisplaySettings(),
    val repair: RepairSettings = RepairSettings(),
    val onboarding: OnboardingState = OnboardingState()
)
